### ISSUE TITLE
Hello author, I am very interested in this work. Can this algorithm be applied to the task allocation of drones in a three-dimensional environment?

### ISSUE THREAD

**Issue by ydhexyk** [MartinBraquet/task-allocation-auctions#3]
Hello author, I am very interested in this work. Can this algorithm be applied to the task allocation of drones in a three-dimensional environment?

**Comment by MartinBraquet** [comment]
Hi @ydhexyk , yes, the algorithm extends to environments of any dimension, but the current code only works in 2 dimensions. To make it work in 3D, you will need to change the size of the vectors and matrices, mostly in OptimalControl_DTA.m. For example, here
https://github.com/MartinBraquet/task-allocation-auctions/blob/4711c6143691a7b67272e4c7260b592288632467/src/OptimalControl_DTA.m#L40-L41
you need to replace the `2`'s with `3`'s. Then you will obtain the task allocation vectors in 3D (for drones for example). If you also want some plots, you'll need to update their functions as well.

**Comment by ydhexyk** [comment]
Thank you for your reply！
